[package]
name = "client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "raft-kv-cli"
path = "src/main.rs"

[dependencies]
tokio   = { workspace = true }
clap    = { workspace = true }
anyhow  = { workspace = true }
reqwest      = { version = "0.12", features = ["json"] }
urlencoding  = "2"
serde_json   = { workspace = true }
